### ISSUE TITLE
GitHub API Deprecation

### ISSUE THREAD

**Issue by danisyellis** [Microsoft/ghrequestor#15]
Hi there, we've been running the GHCrawler for our OSPO. For the last few weeks, when running it we've been getting a notification from GitHub that part of the GitHub API, used by ghrequestor, is being deprecated soon.

> using the `access_token` query parameter is deprecated and will be removed July 1st, 2020

and we need to 

> use the Authorization HTTP header instead

I'm raising the issue here because the email says the problem is happening here, in ghrequestor.

Has the Microsoft OSPO been getting this issue too?

Here's a (slightly anonymized) copy of the email we're getting:

> Hi @danisyellis,

> On February 11th, 2020 at 00:29 (UTC) your personal access token (test - all reads and admin org_hook) using ghrequestor was used as part of a query parameter to access an endpoint through the GitHub API:

> https://api.github.com/user/{userNumber}

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

> Thanks,
The GitHub Team

**Comment by jeffwilcox** [comment]
So sorry @danisyellis we moved past the crawler project to align with a larger internal engineering system that does bulk ingestion a while back, and so this has been deprecated. :/

It's pretty straightforward to update this format now but I'm super sorry we didn't get to it here. It's not a shining example of any good open source collaboration happening that we didn't even have people watching this repo.
